from screeninfo import get_monitors

# GAME
GAME_MAX_ITERATIONS_PER_SECOND = 27
GAME_ITERATION_LAPS_TIME_MS = 0
GAME_LAYOUT = [
    {'floors': 10, 'elevators': 13},
    {'floors': 5, 'elevators': 2}, 
    {'floors': 7, 'elevators': 2}, 
    {'floors': 16, 'elevators': 4}
    ]

GAME_MIN_SCREEN_HEIGHT_PX = 800
GAME_MIN_SCREEN_WIDTH_PX = 500

monitor = get_monitors()[0]
GAME_MAX_SCREEN_HEIGHT_PX = monitor.height - 100
GAME_MAX_SCREEN_WIDTH_PX = monitor.width - 150
GAME_SCROLL_PX_PER_SWIPE = 50
GAME_SCALE_RATE = 0.1
GAME_SCALE_MIN = 0.5
GAME_SCALE_MAX = 1.5

# BULDING
BULDING_WIDTH_PX = 200
BUILDING_GAP_PX = 20

# FLOOR
FLOOR_HEIGHT_PX = 115
FLOOR_BACKGROUND_FILE = './public/floor.jpg'
FLOOR_UNDERLINE_HEIGHT_PX = 7

# FLOOR BUTTON
FLOOR_BUTTON_X = 3 *(BULDING_WIDTH_PX // 8)
FLOOR_BUTTON_Y = FLOOR_HEIGHT_PX // 4
FLOOR_BUTTON_WIDTH = BULDING_WIDTH_PX // 4
FLOOR_BUTTON_HEIGHT = FLOOR_HEIGHT_PX // 2
FLORR_BUTTON_COLLOR_DEFAULT = 'white'
FLORR_BUTTON_COLLOR_WAIT = 'pink'
FLORR_BUTTON_COLLOR_HOLD = 'gray'

# FLOOR TEXT
FLOOR_TEXT_COLOR = 5
FLOOR_TEXT_SIZE = 5
FLOOR_TEXT_X = FLOOR_BUTTON_X + (FLOOR_BUTTON_WIDTH // 3)
FLOOR_TEXT_Y = FLOOR_BUTTON_Y + (FLOOR_BUTTON_HEIGHT // 3)

# ELEVATOR
ELEVATOR_IMG_HEIGHT_PX = 80
ELEVATOR_IMG_WIDTH_PX = 60
MS_PER_FLOOR = 500
MS_WAIT_IN_FLOOR = 2_000
ELEVATOR_BACKGROUND_FILE =  './public/elv.png'
ELEVATOR_DING_FILE =  './public/ding.mp3'
